Updated at 2024-03-26

diff --git a/ENV/bashrc b/ENV/bashrc
--- a/ENV/bashrc
+++ b/ENV/bashrc
@@ -49,3 +49,10 @@ alias gssh='gcloud compute ssh --zone=asia-east2-a'
 alias vmstart='gcloud compute instances start --zone=asia-east2-a'
 alias vmstop='gcloud compute instances stop --zone=asia-east2-a'
 alias gscp='gcloud compute scp --zone=asia-east2-a '
+
+bash /Users/xsong/scripts/update_mac_exlcude_proxy.sh > /dev/null 2>&1
+if [ "x$?" == 'x0' ];then
+   echo "loaded bypass proxy settings"
+else
+   echo "failed to load bypass proxy settings, please check the script [/Users/xsong/scripts/update_mac_exlcude_proxy.sh]"
+fi
